name: trejo_examen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  geolocator: ^11.1.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo_famoso_starbucks.webp
  uses-material-design: true
